#!/bin/env bash

. "$(dirname "$(realpath "$0")")/common.sh"

kill_jobs()
{
	local i
	for i in $(jobs -p)
	do	kill "$@" "$i"
	done
}

start_svc()
{
	host_svc x11 &
	host_svc virgl &
	host_svc pulse &
}

trap "kill_jobs; sleep 0.02; kill_jobs -9" INT TERM HUP
start_svc
## wait for xserver startup
sleep 0.7
c_run xfwm4 &
c_run dbus-launch xfce4-panel &
c_run OpenUtau "$@" &
msg "启动完成"
c_run bash

msg "正在退出..."
kill_jobs
sleep 0.7
kill_jobs -9
