#!/data/data/com.termux/files/usr/bin/zsh -eu

. "$(dirname "$(realpath "$0")")/res/common.zsh" "$0"

msg "$(M W.welcome)"
msg "$(M W.guide)"

msg "$(M W.1.title)"
msg "$(M W.1.pkgs_below)"
package sync || error "$(M W.1.sync_failed)"
package add proot debootstrap termux-x11-nightly virglrenderer-android pulseaudio || \
  error "$(M W.1.add_failed)"

msg "$(M W.2.title)"
if [ $STOR_ACCESS = 1 ]
then msg "$(M W.2.perm_granted)" GREEN
else	msg "$(M W.2.perm_getting)"
	print_run termux-setup-storage || \
	  msg "$(M W.2.perm_denied)"
fi

msg "$(M W.3.title)"
until [ -f $OPU_DIR/OpenUtau ]
do	createdir $OPU_DIR
	msg "$(M W.3.instruction $OPU_DIR)"
	read -r -s "none?$(M W.3.prompt)"
	echo
done
chmod +x $OPU_DIR/OpenUtau
msg "$(M W.3.fin)"

msg "$(M W.4.title)"
if [ -d $C_ROOT ]
then msg "$(M W.4.done)"
else	msg "$(M W.4.desc $C_ROOT $DB_SUITE)"
	read -r "key?[Y/N]"
	case $key in
	Y|y|'') bootstrap;;
	*) error "$(M W.4.cancelled)";;
	esac
fi
msg "$(M W.5.title)"
msg "$(M W.5.desc)"
c_run "$R_DIR/bin/envfix"

msg "(M W.fin)"
